# Generated by Django 5.0.6 on 2024-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
